server:
  port: 8083
mybatis:
  mapper-locations: /mapper/autoMapper/*.xml
  type-aliases-package: spring.skitdatatable.dao

#分库1
spring.datasource.test1.driver-class-name: com.mysql.cj.jdbc.Driver
spring.datasource.test1.jdbc-url: jdbc:mysql://localhost:3306/sharding_0?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=UTC
spring.datasource.test1.username: root
spring.datasource.test1.password: root
#分库2
spring.datasource.test2.driver-class-name: com.mysql.cj.jdbc.Driver
spring.datasource.test2.jdbc-url: jdbc:mysql://localhost:3306/sharding_1?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=UTC
spring.datasource.test2.username: root
spring.datasource.test2.password: root